name: Project Validation Metrics
run-name: Metrics evalation for ${{ github.actor }}'s models at ${{ github.event.repository.updated_at}}

on:
  pull_request:
    branches:
      - main
      - submit-* # Branches that start with submit- are created for each student to submit the final version of their project

permissions:
  contents: write
  pull-requests: write

jobs:
  evaluate-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry export --without-hashes --format=requirements.txt > requirements.txt
          pip install -r requirements.txt

      - name: Run metrics script and capture output
        id: metrics
        run: |
          output=$(python manage.py verify)
          echo "$output" > table_output.txt

      - name: Read table output
        id: read_table
        run: |
          table_content=$(cat table_output.txt)
          echo "TABLE_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$table_content" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post metrics as comment on PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "${{ env.TABLE_CONTENT }}"
